spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.204.129:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Dxw314159
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckInterval: 10s
  thrift:
    server:
      service-id: thrift-rpc-calculator ## 服务ID
      service-model: hsHa ## 服务线程模型simple/nonBlocking/threadPool/hsHa/threadedSelector
      port: 25001
      worker-queue-capacity: 1000
      hs-ha:
        min-worker-threads: 5
        max-worker-threads: 20
        keep-alived-time: 3
  application:
    name: account
  zipkin:
    base-url: http://localhost:9411
server:
  port: 9001

mybatis:
  type-aliases-package: com.dxw.cloud
  mapper-locations: classpath:mapper/*.xml